version: '3.8'

services:
  db:
    image: postgres:15
    container_name: flight_heatmap_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: opensky
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
