// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
)

type AircraftPosition struct {
	ID            int32
	Icao24        sql.NullString
	Callsign      sql.NullString
	OriginCountry sql.NullString
	TimePosition  sql.NullTime
	Longitude     sql.NullFloat64
	Latitude      sql.NullFloat64
	BaroAltitude  sql.NullFloat64
	OnGround      sql.NullBool
	Velocity      sql.NullFloat64
	Heading       sql.NullFloat64
	VerticalRate  sql.NullFloat64
}
