// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"
)

type Querier interface {
	GetAircraftData(ctx context.Context, id int32) (AircraftPosition, error)
	GetHeatmapDataDynamic(ctx context.Context, arg GetHeatmapDataDynamicParams) ([]GetHeatmapDataDynamicRow, error)
	InsertPosition(ctx context.Context, arg InsertPositionParams) error
}

var _ Querier = (*Queries)(nil)
