#!/usr/bin/env bash

set -euo pipefail

CLIENT_ID=$(op read op://Personal/OpenSky-API/client_id)
CLIENT_SECRET=$(op read op://Personal/OpenSky-API/client_secret)
DATABASE_URL=postgresql://postgres:postgres@localhost:5433/opensky?sslmode=disable

echo "Fetching secrets from 1Password..."

cat > server/.env <<EOF
# Auto-generated by scripts/env.sh
OPEN_SKY_CLIENT_ID=$CLIENT_ID
OPEN_SKY_CLIENT_SECRET=$CLIENT_SECRET
DATABASE_URL=$DATABASE_URL
EOF

echo "✅ .env created/updated."
