// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	GetHeatmapData(ctx context.Context) ([]GetHeatmapDataRow, error)
	InsertPosition(ctx context.Context, arg InsertPositionParams) error
}

var _ Querier = (*Queries)(nil)
